bradylangdale/Chromatose

main.py
- Adjusted FOV to 90
- Added player physics
- Added random boxes to interact with
- Closes: #1
=> Add player physics

main.py, playercontroller.py, shaders/colors.frag, shaders/colors.vert
- Add the RGB shaders
- Updates dynamically
- Closes: #6 
@Nuri-G
=> Add dynamic shader code

main.py, playercontroller.py
- Add the gun to the player
Closes: #17
=> Add gun to player model

interactableobject.py, main.py
- Hot fix, objects falling through the ground
=> Fix objects falling through

billboardobject.py, interactableobject.py, main.py, playercontroller.py
- Replaced the kinematic controller with a regular capsule and rigid body
- Fixes interactions with the player and environment
- Includes various other fixes
=> Improve player controller

main.py, pipeline.py, playercontroller.py
- Fixes a jump bug
- Add fullscreen by pressing `F`
=> Add ability to go fullscreen

interactableobject.py, main.py, playercontroller.py
- Add rgb values to the player
- And picks up crystals
- Closes: #30
=> Add ability to pick up crystals

main.py, playercontroller.py
- Added floor animation
- Add and adjusted bloom and exposure settings
- Closes: #50
=> Add the new map and turned on bloom

main.py, playercontroller.py
- Fix the jumping bug, but the player can climb the pillars
=> Fix jumping and adjust shaders

main.py, pausemenu.py, playercontroller.py
Creates pause menu. Not sure if it would have been better to integrate this to the playercontroller instead.
=> Adds Pause menu

main.py, playercontroller.py
The coloring wasn't working I noticed, so this gets around the issue.
I also increased the map size and got shadows working again.
=> Adjusted coloring

crystalobject.py, main.py
=> Add crystals class

Confauto.prc, Config.prc, main.py
- Added a function to convert relative paths to absolute at runtime
- Added config files for Panda3D
Command Used to Build:
```
pyinstaller --noconfirm --onefile --windowed --add-data "C:/Users/brady/Documents/Code/Chromatos/Assets;Assets/" --add-data "C:/Panda3D-1.10.13-x64/direct;direct/" --add-data "C:/Panda3D-1.10.13-x64/panda3d;panda3d/" --add-data "C:/Panda3D-1.10.13-x64/bin;bin/" --paths "C:/Panda3D-1.10.13-x64/panda3d" --paths "C:/Panda3D-1.10.13-x64/bin" --paths "C:/Panda3D-1.10.13-x64/direct" --add-data "C:/Users/brady/Documents/Code/Chromatos/Confauto.prc;." --add-data "C:/Users/brady/Documents/Code/Chromatos/Config.prc;." --paths "C:/Panda3D-1.10.13-x64" --add-data "C:/Panda3D-1.10.13-x64;Panda3D-1.10.13-x64/"  "C:/Users/brady/Documents/Code/Chromatos/main.py"
```
=> Add necessary changes to build EXE

main.py
Just added in the new enemies so we could see them in the environment.
=> Add enemies billboards

bulletmanager.py, main.py, playercontroller.py
- Adjusted color position
- Fixed loading resource error
=> Adjust UI and colors

bulletmanager.py, main.py, playercontroller.py
=> Add more pillars

Config.prc, billboardobject.py, enemyspawner.py, main.py, pausemenu.py, playercontroller.py, startscreen.py
- Adds more enemy spawners
- Adds enemy drops
- Improves the UI look
- Displays the score during the game
- Displays pause menu
- Displays retry menu
=> Fixes from game flow issues

billboardobject.py, bulletmanager.py, main.py, playercontroller.py
- Removes crystals and bullets on reset
- Increases difficulty
- Increases ammo and shield time
=> Brady cleanup scene

main.py, playercontroller.py
- Added pillars to 0, 0
- Added spawners on left and right edges
=> Add new pillar and spawners

billboardobject.py, main.py
=> made weaker more enemies

README.md
just some basic info like rules and what the colors mean
=> Added basic info such as rules

billboardobject.py, bulletmanager.py, crystalobject.py, playercontroller.py
I noticed the game was slowing down the more you played. It seems to be an issue with tasks not being removed once the object was and enemies just sitting around.
=> Optimize game
